// ─── MATCHES ───────────────────────────────────────────────
export const MATCHES = [
  {
    id: 1,
    home: "Inter", homeShort: "INT",
    away: "Milan", awayShort: "MIL",
    league: "Serie A", leagueShort: "SA",
    date: "Oggi", time: "20:45",
    status: "today",
    prob: { home: 45, draw: 28, away: 27 },
    odds: { home: 2.40, draw: 3.10, away: 2.90 },
    ou: { over15: 1.30, under15: 3.40, over25: 1.80, under25: 2.00, over35: 3.10, under35: 1.35 },
    gg: { goal: 1.72, noGoal: 2.05 },
    xg: { home: 1.78, away: 1.22 },
    valueBet: { type: "1", edge: 12, market: "1X2" },
    scores: [
      { score: "2:1", prob: 16 }, { score: "1:1", prob: 14 }, { score: "2:2", prob: 11 },
    ],
    confidence: 83,
    scorers: [
      { name: "Lautaro Martinez", odds: 2.10, prob: 38, xg: 0.63 },
      { name: "Thuram", odds: 2.80, prob: 29, xg: 0.45 },
      { name: "Leão", odds: 3.20, prob: 25, xg: 0.38 },
    ],
    bookmakers: [
      { name: "Bet365", home: 2.40, draw: 3.10, away: 2.90, best: true },
      { name: "SNAI", home: 2.35, draw: 3.05, away: 2.85 },
      { name: "Sisal", home: 2.38, draw: 3.00, away: 2.80 },
      { name: "Planetwin365", home: 2.30, draw: 3.15, away: 2.95 },
    ],
    homeForm: ["V","V","P","V","V"],
    awayForm: ["V","S","V","P","S"],
    h2h: [
      { date: "15/03/25", home: "Inter", away: "Milan", score: "2-1" },
      { date: "20/10/24", home: "Milan", away: "Inter", score: "1-1" },
      { date: "05/02/24", home: "Inter", away: "Milan", score: "1-0" },
      { date: "22/10/23", home: "Milan", away: "Inter", score: "0-1" },
      { date: "19/02/23", home: "Inter", away: "Milan", score: "1-0" },
    ],
    badges: ["Squadra in forma", "Trend Over 2.5", "Value bet"],
    injuries: [
      { name: "de Vrij", team: "Inter", status: "assente" },
      { name: "Bennacer", team: "Milan", status: "dubbio" },
    ],
    live: null,
  },
  {
    id: 2,
    home: "Juventus", homeShort: "JUV",
    away: "Napoli", awayShort: "NAP",
    league: "Serie A", leagueShort: "SA",
    date: "Domani", time: "18:00",
    status: "tomorrow",
    prob: { home: 38, draw: 30, away: 32 },
    odds: { home: 2.65, draw: 3.20, away: 2.75 },
    ou: { over15: 1.35, under15: 3.20, over25: 1.95, under25: 1.88, over35: 3.30, under35: 1.30 },
    gg: { goal: 1.80, noGoal: 1.95 },
    xg: { home: 1.45, away: 1.52 },
    valueBet: null,
    scores: [
      { score: "1:1", prob: 18 }, { score: "1:2", prob: 14 }, { score: "2:1", prob: 13 },
    ],
    confidence: 64,
    scorers: [
      { name: "Vlahovic", odds: 2.50, prob: 32, xg: 0.55 },
      { name: "Osimhen", odds: 2.30, prob: 35, xg: 0.60 },
      { name: "Kvaratskhelia", odds: 3.10, prob: 26, xg: 0.40 },
    ],
    bookmakers: [
      { name: "Bet365", home: 2.65, draw: 3.20, away: 2.75, best: false },
      { name: "SNAI", home: 2.70, draw: 3.15, away: 2.70, best: true },
      { name: "Sisal", home: 2.60, draw: 3.25, away: 2.80 },
      { name: "Planetwin365", home: 2.55, draw: 3.10, away: 2.75 },
    ],
    homeForm: ["V","P","P","V","S"],
    awayForm: ["V","V","V","P","V"],
    h2h: [
      { date: "20/01/25", home: "Juventus", away: "Napoli", score: "2-2" },
      { date: "12/05/24", home: "Napoli", away: "Juventus", score: "0-0" },
    ],
    badges: ["Derby di campionato", "Trend Goal"],
    injuries: [{ name: "Locatelli", team: "Juventus", status: "dubbio" }],
    live: null,
  },
  {
    id: 3,
    home: "Roma", homeShort: "ROM",
    away: "Lazio", awayShort: "LAZ",
    league: "Serie A", leagueShort: "SA",
    date: "Domani", time: "20:45",
    status: "tomorrow",
    prob: { home: 42, draw: 27, away: 31 },
    odds: { home: 2.35, draw: 3.40, away: 3.10 },
    ou: { over15: 1.28, under15: 3.60, over25: 1.75, under25: 2.05, over35: 2.90, under35: 1.40 },
    gg: { goal: 1.65, noGoal: 2.15 },
    xg: { home: 1.65, away: 1.30 },
    valueBet: { type: "Over 2.5", edge: 8, market: "O/U" },
    scores: [
      { score: "2:1", prob: 15 }, { score: "1:0", prob: 13 }, { score: "2:2", prob: 10 },
    ],
    confidence: 71,
    scorers: [
      { name: "Dybala", odds: 2.90, prob: 28, xg: 0.48 },
      { name: "Lukaku", odds: 2.60, prob: 31, xg: 0.52 },
      { name: "Immobile", odds: 2.70, prob: 30, xg: 0.50 },
    ],
    bookmakers: [
      { name: "Bet365", home: 2.35, draw: 3.40, away: 3.10, best: true },
      { name: "SNAI", home: 2.30, draw: 3.35, away: 3.05 },
      { name: "Sisal", home: 2.38, draw: 3.30, away: 3.00 },
      { name: "Planetwin365", home: 2.32, draw: 3.45, away: 3.15 },
    ],
    homeForm: ["V","V","V","P","V"],
    awayForm: ["V","P","V","V","P"],
    h2h: [
      { date: "05/05/24", home: "Lazio", away: "Roma", score: "1-0" },
      { date: "15/01/24", home: "Roma", away: "Lazio", score: "1-1" },
    ],
    badges: ["Derby della Capitale", "Possibile Over", "Difesa fragile"],
    injuries: [],
    live: null,
  },
  {
    id: 4,
    home: "Manchester Utd", homeShort: "MNU",
    away: "Liverpool", awayShort: "LIV",
    league: "Premier League", leagueShort: "PL",
    date: "Sab 12 Apr", time: "17:30",
    status: "weekend",
    prob: { home: 30, draw: 25, away: 45 },
    odds: { home: 3.40, draw: 3.50, away: 2.10 },
    ou: { over15: 1.25, under15: 3.80, over25: 1.70, under25: 2.10, over35: 2.80, under35: 1.42 },
    gg: { goal: 1.62, noGoal: 2.20 },
    xg: { home: 1.10, away: 1.85 },
    valueBet: { type: "2", edge: 10, market: "1X2" },
    scores: [
      { score: "0:2", prob: 14 }, { score: "1:2", prob: 13 }, { score: "1:1", prob: 12 },
    ],
    confidence: 78,
    scorers: [
      { name: "Salah", odds: 2.20, prob: 36, xg: 0.70 },
      { name: "Diaz L.", odds: 2.80, prob: 28, xg: 0.45 },
      { name: "Rashford", odds: 3.50, prob: 23, xg: 0.30 },
    ],
    bookmakers: [
      { name: "Bet365", home: 3.40, draw: 3.50, away: 2.10, best: true },
      { name: "SNAI", home: 3.30, draw: 3.45, away: 2.05 },
      { name: "Sisal", home: 3.35, draw: 3.40, away: 2.08 },
      { name: "Planetwin365", home: 3.25, draw: 3.55, away: 2.12 },
    ],
    homeForm: ["S","P","S","P","V"],
    awayForm: ["V","V","V","P","V"],
    h2h: [
      { date: "10/03/25", home: "Liverpool", away: "Man Utd", score: "2-0" },
      { date: "07/12/24", home: "Man Utd", away: "Liverpool", score: "0-3" },
    ],
    badges: ["Value bet", "Trend 2"],
    injuries: [{ name: "Rashford", team: "Man Utd", status: "dubbio" }],
    live: null,
  },
  {
    id: 5,
    home: "PSG", homeShort: "PSG",
    away: "Barcelona", awayShort: "BAR",
    league: "Champions League", leagueShort: "UCL",
    date: "Mar 15 Apr", time: "21:00",
    status: "upcoming",
    prob: { home: 40, draw: 26, away: 34 },
    odds: { home: 2.50, draw: 3.30, away: 2.80 },
    ou: { over15: 1.28, under15: 3.60, over25: 1.68, under25: 2.18, over35: 2.75, under35: 1.45 },
    gg: { goal: 1.58, noGoal: 2.28 },
    xg: { home: 1.70, away: 1.55 },
    valueBet: { type: "Goal", edge: 6, market: "GG/NG" },
    scores: [
      { score: "2:2", prob: 12 }, { score: "2:1", prob: 14 }, { score: "1:1", prob: 15 },
    ],
    confidence: 69,
    scorers: [
      { name: "Mbappé", odds: 1.90, prob: 42, xg: 0.80 },
      { name: "Lewandowski", odds: 2.10, prob: 38, xg: 0.72 },
      { name: "Dembélé", odds: 3.00, prob: 27, xg: 0.42 },
    ],
    bookmakers: [
      { name: "Bet365", home: 2.50, draw: 3.30, away: 2.80, best: true },
      { name: "SNAI", home: 2.45, draw: 3.25, away: 2.75 },
      { name: "Sisal", home: 2.52, draw: 3.20, away: 2.78 },
      { name: "Planetwin365", home: 2.48, draw: 3.35, away: 2.82 },
    ],
    homeForm: ["V","V","V","P","V"],
    awayForm: ["V","V","P","V","V"],
    h2h: [
      { date: "10/04/24", home: "PSG", away: "Barcelona", score: "4-1" },
      { date: "16/04/24", home: "Barcelona", away: "PSG", score: "1-4" },
    ],
    badges: ["Big Match", "Goal Atteso", "Alta Qualità"],
    injuries: [{ name: "Hernandez", team: "PSG", status: "assente" }],
    live: null,
  },
  {
    id: 6,
    home: "Real Madrid", homeShort: "RMA",
    away: "Atletico Madrid", awayShort: "ATM",
    league: "La Liga", leagueShort: "LL",
    date: "Sab 12 Apr", time: "21:00",
    status: "weekend",
    prob: { home: 48, draw: 28, away: 24 },
    odds: { home: 2.10, draw: 3.40, away: 3.60 },
    ou: { over15: 1.32, under15: 3.30, over25: 1.85, under25: 1.95, over35: 3.20, under35: 1.33 },
    gg: { goal: 1.75, noGoal: 2.02 },
    xg: { home: 1.90, away: 1.20 },
    valueBet: { type: "1", edge: 5, market: "1X2" },
    scores: [
      { score: "2:0", prob: 18 }, { score: "2:1", prob: 16 }, { score: "1:0", prob: 14 },
    ],
    confidence: 74,
    scorers: [
      { name: "Benzema", odds: 2.30, prob: 35, xg: 0.65 },
      { name: "Vinicius Jr", odds: 2.60, prob: 30, xg: 0.55 },
      { name: "Griezmann", odds: 3.20, prob: 25, xg: 0.40 },
    ],
    bookmakers: [
      { name: "Bet365", home: 2.10, draw: 3.40, away: 3.60, best: true },
      { name: "SNAI", home: 2.05, draw: 3.35, away: 3.55 },
      { name: "Sisal", home: 2.08, draw: 3.45, away: 3.50 },
      { name: "Planetwin365", home: 2.12, draw: 3.30, away: 3.65 },
    ],
    homeForm: ["V","V","V","V","P"],
    awayForm: ["P","V","P","V","V"],
    h2h: [
      { date: "04/02/25", home: "Atletico", away: "Real", score: "1-2" },
      { date: "29/09/24", home: "Real", away: "Atletico", score: "3-1" },
    ],
    badges: ["Squadra in forma", "Clean Sheet Trend"],
    injuries: [],
    live: null,
  },
  {
    id: 7,
    home: "Bayern Monaco", homeShort: "BAY",
    away: "Dortmund", awayShort: "BVB",
    league: "Bundesliga", leagueShort: "BL",
    date: "Dom 13 Apr", time: "18:30",
    status: "weekend",
    prob: { home: 52, draw: 24, away: 24 },
    odds: { home: 1.90, draw: 3.70, away: 4.00 },
    ou: { over15: 1.20, under15: 4.20, over25: 1.55, under25: 2.40, over35: 2.20, under35: 1.62 },
    gg: { goal: 1.58, noGoal: 2.30 },
    xg: { home: 2.10, away: 1.35 },
    valueBet: { type: "Over 2.5", edge: 9, market: "O/U" },
    scores: [
      { score: "3:1", prob: 15 }, { score: "2:1", prob: 14 }, { score: "2:0", prob: 13 },
    ],
    confidence: 81,
    scorers: [
      { name: "Kane", odds: 1.80, prob: 48, xg: 0.88 },
      { name: "Gnabry", odds: 2.90, prob: 28, xg: 0.42 },
      { name: "Malen", odds: 3.40, prob: 22, xg: 0.35 },
    ],
    bookmakers: [
      { name: "Bet365", home: 1.90, draw: 3.70, away: 4.00, best: true },
      { name: "SNAI", home: 1.88, draw: 3.65, away: 3.90 },
      { name: "Sisal", home: 1.92, draw: 3.60, away: 3.95 },
      { name: "Planetwin365", home: 1.85, draw: 3.75, away: 4.10 },
    ],
    homeForm: ["V","V","V","P","V"],
    awayForm: ["V","S","V","P","P"],
    h2h: [
      { date: "01/11/24", home: "Dortmund", away: "Bayern", score: "1-2" },
      { date: "30/03/24", home: "Bayern", away: "Dortmund", score: "2-2" },
    ],
    badges: ["Der Klassiker", "Goleada attesa", "Value Over"],
    injuries: [],
    live: null,
  },
  {
    id: 8,
    home: "Marseille", homeShort: "OM",
    away: "Lyon", awayShort: "OL",
    league: "Ligue 1", leagueShort: "L1",
    date: "Dom 13 Apr", time: "17:00",
    status: "weekend",
    prob: { home: 44, draw: 28, away: 28 },
    odds: { home: 2.25, draw: 3.30, away: 3.20 },
    ou: { over15: 1.33, under15: 3.25, over25: 1.88, under25: 1.92, over35: 3.15, under35: 1.35 },
    gg: { goal: 1.70, noGoal: 2.10 },
    xg: { home: 1.55, away: 1.40 },
    valueBet: null,
    scores: [
      { score: "1:1", prob: 17 }, { score: "2:1", prob: 14 }, { score: "1:0", prob: 13 },
    ],
    confidence: 58,
    scorers: [
      { name: "Aubameyang", odds: 2.80, prob: 30, xg: 0.50 },
      { name: "Lacazette", odds: 3.00, prob: 27, xg: 0.45 },
    ],
    bookmakers: [
      { name: "Bet365", home: 2.25, draw: 3.30, away: 3.20, best: true },
      { name: "SNAI", home: 2.20, draw: 3.25, away: 3.15 },
      { name: "Sisal", home: 2.28, draw: 3.35, away: 3.18 },
      { name: "Planetwin365", home: 2.22, draw: 3.20, away: 3.25 },
    ],
    homeForm: ["V","P","V","P","V"],
    awayForm: ["S","V","P","S","V"],
    h2h: [
      { date: "25/08/24", home: "Lyon", away: "Marseille", score: "1-1" },
    ],
    badges: [],
    injuries: [],
    live: null,
  },
];

// ─── LIVE MATCH ────────────────────────────────────────────
export const LIVE_MATCH = {
  id: 1,
  home: "Inter", homeShort: "INT",
  away: "Milan", awayShort: "MIL",
  homeScore: 1, awayScore: 0,
  minute: 63,
  league: "Serie A",
  stats: {
    shots: { home: 12, away: 7 },
    shotsOnTarget: { home: 5, away: 2 },
    corners: { home: 6, away: 3 },
    attacks: { home: 52, away: 38 },
    dangerousAttacks: { home: 28, away: 15 },
    possession: { home: 58, away: 42 },
    fouls: { home: 8, away: 11 },
    yellowCards: { home: 1, away: 2 },
    xgLive: { home: 1.42, away: 0.68 },
  },
  liveOdds: {
    over25: 1.50, goal: 1.70,
    homeWin: 1.45, draw: 4.20, awayWin: 6.50,
    nextGoalHome: 1.55, nextGoalAway: 2.80,
  },
  dangerIndex: 78,
  dangerMessage: "Alta pressione offensiva dell'Inter. Possibile gol nei prossimi 10 minuti.",
  dangerHistory: [30, 35, 55, 48, 62, 70, 75, 78],
  events: [
    { minute: 12, type: "dangerous", team: "home", player: null },
    { minute: 23, type: "yellow", team: "away", player: "Bennacer" },
    { minute: 34, type: "goal", team: "home", player: "Lautaro Martinez" },
    { minute: 41, type: "dangerous", team: "away", player: null },
    { minute: 45, type: "yellow", team: "home", player: "Barella" },
    { minute: 58, type: "substitution", team: "away", player: "Giroud" },
    { minute: 63, type: "dangerous", team: "home", player: null },
  ],
};

export const LIVE_MATCHES = [
  LIVE_MATCH,
  {
    id: 99,
    home: "Arsenal", homeShort: "ARS",
    away: "Chelsea", awayShort: "CHE",
    homeScore: 2, awayScore: 1,
    minute: 78,
    league: "Premier League",
    stats: {
      shots: { home: 14, away: 10 },
      shotsOnTarget: { home: 6, away: 4 },
      corners: { home: 8, away: 4 },
      attacks: { home: 58, away: 44 },
      dangerousAttacks: { home: 32, away: 20 },
      possession: { home: 55, away: 45 },
      fouls: { home: 10, away: 9 },
      yellowCards: { home: 2, away: 1 },
      xgLive: { home: 2.20, away: 1.40 },
    },
    liveOdds: { over25: 1.20, goal: 1.30, homeWin: 1.25, draw: 5.00, awayWin: 9.00 },
    dangerIndex: 45,
    dangerMessage: "Match controllato dall'Arsenal. Possibile terzo gol.",
    dangerHistory: [40, 48, 50, 52, 44, 46, 44, 45],
    events: [
      { minute: 15, type: "goal", team: "home", player: "Saka" },
      { minute: 42, type: "goal", team: "away", player: "Palmer" },
      { minute: 65, type: "goal", team: "home", player: "Martinelli" },
    ],
  },
];

// ─── LINEUPS ───────────────────────────────────────────────
export const INTER_LINEUP = {
  formation: "3-5-2",
  players: [
    { name: "Sommer", pos: "GK", x: 50, y: 88, status: "confermato", number: 1 },
    { name: "Pavard", pos: "DC", x: 22, y: 72, status: "confermato", number: 28 },
    { name: "Acerbi", pos: "DC", x: 50, y: 75, status: "confermato", number: 15 },
    { name: "Bastoni", pos: "DC", x: 78, y: 72, status: "confermato", number: 95 },
    { name: "Dumfries", pos: "RM", x: 12, y: 53, status: "confermato", number: 2 },
    { name: "Barella", pos: "CM", x: 35, y: 53, status: "confermato", number: 23 },
    { name: "Calhanoglu", pos: "CM", x: 50, y: 58, status: "confermato", number: 20 },
    { name: "Mkhitaryan", pos: "CM", x: 65, y: 53, status: "probabile", number: 22 },
    { name: "Dimarco", pos: "LM", x: 88, y: 53, status: "confermato", number: 32 },
    { name: "Lautaro", pos: "FW", x: 38, y: 28, status: "confermato", number: 10 },
    { name: "Thuram", pos: "FW", x: 62, y: 28, status: "confermato", number: 9 },
  ],
};

export const MILAN_LINEUP = {
  formation: "4-2-3-1",
  players: [
    { name: "Maignan", pos: "GK", x: 50, y: 88, status: "confermato", number: 16 },
    { name: "Calabria", pos: "RB", x: 15, y: 70, status: "confermato", number: 2 },
    { name: "Tomori", pos: "CB", x: 38, y: 73, status: "confermato", number: 23 },
    { name: "Thiaw", pos: "CB", x: 62, y: 73, status: "probabile", number: 28 },
    { name: "Theo", pos: "LB", x: 85, y: 70, status: "confermato", number: 19 },
    { name: "Bennacer", pos: "CM", x: 38, y: 55, status: "dubbio", number: 4 },
    { name: "Reijnders", pos: "CM", x: 62, y: 55, status: "confermato", number: 14 },
    { name: "Pulisic", pos: "RW", x: 20, y: 38, status: "confermato", number: 11 },
    { name: "Chukwueze", pos: "CAM", x: 50, y: 40, status: "probabile", number: 21 },
    { name: "Leão", pos: "LW", x: 80, y: 38, status: "confermato", number: 10 },
    { name: "Morata", pos: "ST", x: 50, y: 23, status: "confermato", number: 7 },
  ],
};

// ─── PLAYERS ───────────────────────────────────────────────
export const PLAYERS = [
  { id: 1, name: "Lautaro Martinez", team: "Inter", pos: "Attaccante", number: 10, xg: 0.63, shots: 3.2, fouls: 1.1, minutes: 87, form: "Eccellente", formHistory: [1,0,2,1,1], scorerOdds: 2.10, scorerProb: 38, goals: 18, assists: 5, insight: "In grande forma. Nelle ultime 5 giornate ha segnato 4 gol e servito 2 assist." },
  { id: 2, name: "Thuram", team: "Inter", pos: "Attaccante", number: 9, xg: 0.45, shots: 2.8, fouls: 0.9, minutes: 83, form: "Ottima", formHistory: [1,1,0,1,0], scorerOdds: 2.80, scorerProb: 29, goals: 12, assists: 7, insight: "Pericoloso in profondità. Buon movimento senza palla." },
  { id: 3, name: "Barella", team: "Inter", pos: "Centrocampista", number: 23, xg: 0.15, shots: 1.8, fouls: 2.1, minutes: 90, form: "Eccellente", formHistory: [0,1,1,1,1], scorerOdds: 5.50, scorerProb: 12, goals: 4, assists: 9, insight: "Box to box dominante. Colonna portante del gioco interista." },
  { id: 4, name: "Calhanoglu", team: "Inter", pos: "Centrocampista", number: 20, xg: 0.25, shots: 2.1, fouls: 1.8, minutes: 88, form: "Buona", formHistory: [0,1,0,1,1], scorerOdds: 4.00, scorerProb: 18, goals: 7, assists: 10, insight: "Regista avanzato con ottima lettura del gioco. Specialista su calci piazzati." },
  { id: 5, name: "Leão", team: "Milan", pos: "Ala", number: 10, xg: 0.38, shots: 2.5, fouls: 1.5, minutes: 85, form: "Buona", formHistory: [1,0,1,0,1], scorerOdds: 3.20, scorerProb: 25, goals: 10, assists: 8, insight: "Velocità letale sulla sinistra. Pericoloso nelle transizioni rapide." },
  { id: 6, name: "Pulisic", team: "Milan", pos: "Ala", number: 11, xg: 0.35, shots: 2.2, fouls: 1.3, minutes: 82, form: "Ottima", formHistory: [1,1,0,1,1], scorerOdds: 3.50, scorerProb: 22, goals: 9, assists: 6, insight: "Tecnica e pressing alto. Uno dei migliori della stagione nel Milan." },
  { id: 7, name: "Morata", team: "Milan", pos: "Attaccante", number: 7, xg: 0.52, shots: 2.9, fouls: 1.7, minutes: 80, form: "Media", formHistory: [0,1,0,0,1], scorerOdds: 2.90, scorerProb: 27, goals: 11, assists: 4, insight: "Presenza fisica in area. Ha bisogno di rifornimenti di qualità." },
];

// ─── MULTI-BET ─────────────────────────────────────────────
export const MULTI_BET = {
  selections: [
    { home: "Inter", away: "Milan", league: "Serie A", date: "Oggi - 20:45", market: "1 (Inter vince)", odds: 2.45, confidence: 83 },
    { home: "Manchester Utd", away: "Liverpool", league: "Premier League", date: "Sab - 17:30", market: "Over 2.5", odds: 1.67, confidence: 76 },
    { home: "PSG", away: "Barcelona", league: "Champions League", date: "Mar - 21:00", market: "Goal", odds: 1.55, confidence: 88 },
  ],
  bookmakers: [
    { name: "Bet365", odds: 6.34, best: true },
    { name: "SNAI", odds: 6.18, value: "+2%", valueAmount: "€32" },
    { name: "Sisal", odds: 6.15 },
    { name: "Planetwin365", odds: 6.04 },
  ],
};

export const MULTI_BET_COMBOS = [
  {
    id: 1, type: "algoritmiche", tag: "Bilanciata",
    odds: 6.34, confidence: 83, risk: "medio",
    potentialWin: 634,
    selections: [
      { home: "Inter", away: "Milan", market: "1", odds: 2.45, confidence: 83, league: "Serie A" },
      { home: "Man Utd", away: "Liverpool", market: "Over 2.5", odds: 1.67, confidence: 76, league: "PL" },
      { home: "PSG", away: "Barcelona", market: "Goal", odds: 1.55, confidence: 88, league: "UCL" },
    ],
    bookmakers: [{ name: "Bet365", odds: 6.34, best: true }, { name: "SNAI", odds: 6.18 }, { name: "Sisal", odds: 6.15 }],
  },
  {
    id: 2, type: "safe", tag: "Conservativa",
    odds: 2.88, confidence: 91, risk: "basso",
    potentialWin: 288,
    selections: [
      { home: "Bayern Monaco", away: "Dortmund", market: "Over 1.5", odds: 1.22, confidence: 94, league: "BL" },
      { home: "Real Madrid", away: "Atletico", market: "1 o X", odds: 1.45, confidence: 89, league: "LL" },
      { home: "Inter", away: "Milan", market: "Goal", odds: 1.63, confidence: 88, league: "SA" },
    ],
    bookmakers: [{ name: "Bet365", odds: 2.88, best: true }, { name: "SNAI", odds: 2.81 }, { name: "Sisal", odds: 2.85 }],
  },
  {
    id: 3, type: "value", tag: "Aggressiva",
    odds: 14.20, confidence: 62, risk: "alto",
    potentialWin: 1420,
    selections: [
      { home: "Inter", away: "Milan", market: "2+ Gol Int", odds: 2.90, confidence: 65, league: "SA" },
      { home: "Man Utd", away: "Liverpool", market: "2 (Liverpool)", odds: 2.10, confidence: 72, league: "PL" },
      { home: "Bayern Monaco", away: "Dortmund", market: "Over 3.5", odds: 2.20, confidence: 60, league: "BL" },
      { home: "PSG", away: "Barcelona", market: "1 (PSG)", odds: 2.50, confidence: 60, league: "UCL" },
    ],
    bookmakers: [{ name: "Bet365", odds: 14.20, best: true }, { name: "SNAI", odds: 13.80 }, { name: "Sisal", odds: 14.10 }],
  },
];

export const LEAGUES = ["Serie A", "Premier League", "La Liga", "Bundesliga", "Ligue 1", "Champions League"];
