export const legalProcessors = [
  {
    service: "Vercel",
    role: "Hosting/CDN",
    category: "Infrastructure",
    purpose: "Deploy frontend e distribuzione contenuti",
    region: "EU/US (da verificare per progetto)",
    externalUrl: "https://vercel.com/legal",
    notes: "Placeholder: verificare piano, region pinning e DPA.",
  },
  {
    service: "Railway",
    role: "Backend hosting",
    category: "Infrastructure",
    purpose: "Esecuzione servizi backend e processi applicativi",
    region: "Da confermare",
    externalUrl: "https://railway.com/legal",
    notes: "Placeholder: confermare data residency e retention log.",
  },
  {
    service: "Telegram",
    role: "Messaging platform",
    category: "Communication",
    purpose: "Invio messaggi/canale e bot",
    region: "Globale",
    externalUrl: "https://telegram.org/privacy",
    notes: "Placeholder: verificare base giuridica e ruolo titolare/responsabile.",
  },
  {
    service: "MongoDB Atlas",
    role: "Database",
    category: "Data Storage",
    purpose: "Persistenza dati applicativi",
    region: "Da confermare",
    externalUrl: "https://www.mongodb.com/legal/privacy-policy",
    notes: "Placeholder: verificare cluster region e cifratura.",
  },
  {
    service: "Stripe",
    role: "Payment processor",
    category: "Billing",
    purpose: "Checkout, fatturazione e gestione pagamenti",
    region: "Globale",
    externalUrl: "https://stripe.com/privacy",
    notes: "Placeholder: mappare flussi billing e documentazione fiscale.",
  },
  {
    service: "Analytics Provider",
    role: "Analytics",
    category: "Measurement",
    purpose: "Metriche di uso e performance",
    region: "Da confermare",
    externalUrl: "",
    notes: "Placeholder: sostituire con provider effettivo e policy ufficiale.",
  },
];
